# Generated by Django 4.2 on 2025-12-12 22:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appusuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='razas', to='appmascotas.especie')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=6)),
                ('edad', models.PositiveIntegerField(default=0)),
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now)),
                ('notas', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imgmascota')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='appusuarios.cliente')),
                ('especie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appmascotas.especie')),
                ('raza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appmascotas.raza')),
            ],
        ),
    ]
