# Generated by Django 4.2 on 2026-03-22 21:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appmascotas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especie',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='mascota',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='raza',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterField(
            model_name='especie',
            name='nombre',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='fecha_alta',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='raza',
            unique_together={('especie', 'nombre')},
        ),
        migrations.AddIndex(
            model_name='mascota',
            index=models.Index(fields=['cliente', 'nombre'], name='appmascotas_cliente_e7c8e6_idx'),
        ),
    ]
