# Generated by Django 4.2 on 2026-03-10 23:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReseniaRestApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.TextField(blank=True, null=True)),
                ('puntuacion', models.PositiveIntegerField(choices=[(1, '1 / 5 Estrellas'), (2, '2 / 5 Estrellas'), (3, '3 / 5 Estrellas'), (4, '4 / 5 Estrellas'), (5, '5 / 5 Estrellas')], default=5)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('aprobada', models.BooleanField(default=False)),
            ],
        ),
    ]
