# Generated by Django 4.2 on 2026-01-17 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appusuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombre',
        ),
    ]
