# Generated by Django 4.2 on 2025-10-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('edad', models.CharField(max_length=3)),
                ('especie', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=10)),
                ('consulta', models.CharField(max_length=500)),
                ('fecha_creacion', models.DateTimeField(verbose_name='Fecha de Creación')),
                ('fecha_edicion', models.DateTimeField(verbose_name='Fecha de Modificación')),
            ],
        ),
    ]
