# Generated by Django 4.2 on 2025-12-12 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdegestion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mascota',
        ),
    ]
