# Generated by Django 4.2 on 2025-12-12 22:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appusuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.PositiveIntegerField(choices=[(1, '1 / 5 Estrellas'), (2, '2 / 5 Estrellas'), (3, '3 / 5 Estrellas'), (4, '4 / 5 Estrellas'), (5, '5 / 5 Estrellas')], default=5)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenias', to='appusuarios.cliente')),
            ],
        ),
    ]
