# Generated by Django 4.2 on 2026-01-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appresenias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resenia',
            name='aprobada',
            field=models.BooleanField(default=False),
        ),
    ]
