# Generated by Django 4.2 on 2026-03-22 23:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appresenias', '0002_resenia_aprobada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resenia',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterField(
            model_name='resenia',
            name='aprobada',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='resenia',
            name='fecha',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='resenia',
            name='puntuacion',
            field=models.PositiveIntegerField(choices=[(1, '1 / 5 Estrellas'), (2, '2 / 5 Estrellas'), (3, '3 / 5 Estrellas'), (4, '4 / 5 Estrellas'), (5, '5 / 5 Estrellas')], db_index=True, default=5),
        ),
        migrations.AddIndex(
            model_name='resenia',
            index=models.Index(fields=['cliente', 'fecha'], name='appresenias_cliente_022b3e_idx'),
        ),
        migrations.AddIndex(
            model_name='resenia',
            index=models.Index(fields=['aprobada', 'fecha'], name='appresenias_aprobad_3721c8_idx'),
        ),
    ]
