# Generated by Django 4.2 on 2026-03-23 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appinventario', '0003_alter_producto_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='tipoproducto',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='appinventario.tipoproducto'),
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre'], name='appinventar_nombre_19835e_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['tipo'], name='appinventar_tipo_id_c0e3f2_idx'),
        ),
    ]
